<?php
return [
  'users'    => ['create', 'edit', 'delete', 'view'],
  'roles'    => ['create', 'edit', 'delete', 'view'],
  'bookings' => ['create', 'edit', 'delete', 'view'],
  'cancel_reasons' => ['create', 'edit', 'delete', 'view'],
  'services' => ['create', 'edit', 'delete', 'view'],
  'products' => ['create', 'edit', 'delete', 'view'],
  'packages' => ['create', 'edit', 'delete', 'view'],
  'package_subscriptions' => ['create', 'edit', 'delete', 'view'],
  'employees' => ['create', 'edit', 'delete', 'view'],
  'customers' => ['create', 'edit', 'delete', 'view'],
  'points'   => ['create', 'edit', 'delete', 'view'],
  'wallets'   => ['create', 'edit', 'delete', 'view'],
  'promotions'   => ['create', 'edit', 'delete', 'view'],
  'promotion_coupons'   => ['create', 'edit', 'delete', 'view'],
  'invoices'   => ['view'],
  'payments'   => ['view'],
  'customer_groups'   => ['create', 'edit', 'delete', 'view'],
  'zones'   => ['create', 'edit', 'delete', 'view'],
  'branches'   => ['create', 'edit', 'delete', 'view'],
  'carousel_items'   => ['create', 'edit', 'delete', 'view'],
  'notifications'   => ['create', 'edit', 'delete', 'view'],
  'app_pages'   => ['create', 'edit', 'delete', 'view']
];
